name: Stockbit Bot

on:
  workflow_dispatch:

  schedule:
    # WIB = UTC+7
    # Senin - Jumat

    # 08:55 WIB
    - cron: "55 1 * * 1-5"

    # 10:00 WIB
    - cron: "0 3 * * 1-5"

    # 11:45 WIB
    - cron: "45 4 * * 1-5"

    # 13:35 WIB
    - cron: "35 6 * * 1-5"

    # 14:30 WIB
    - cron: "30 7 * * 1-5"

    # 15:45 WIB
    - cron: "45 8 * * 1-5"

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show server time
        run: |
          echo "UTC Time:"
          date -u

          echo "WIB Time:"
          TZ=Asia/Jakarta date

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GOAPI_KEY: ${{ secrets.GOAPI_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: python main.py
